"""
Nutrition database for common foods.
All values are per 100g of the food item.
"""

# Nutrition database for common foods (per 100g)
NUTRITION_DATABASE = {
    "apple": {
        "calories": 52,
        "fat": 0.2,
        "protein": 0.3,
        "carbohydrates": 14,
        "micronutrients": {
            "vitamin_c": 4.6,
            "iron": 0.3,
            "calcium": 6,
            "vitamin_d": 0,
            "vitamin_a": 3,
            "vitamin_b12": 0,
            "vitamin_b6": 0.04,
            "folate": 3,
            "magnesium": 5,
            "potassium": 107,
            "zinc": 0.04,
            "selenium": 0.1,
            "copper": 0.04,
            "manganese": 0.03,
            "iodine": 0,
        },
    },
    "banana": {
        "calories": 89,
        "fat": 0.3,
        "protein": 1.1,
        "carbohydrates": 23,
        "micronutrients": {
            "vitamin_c": 8.7,
            "iron": 0.3,
            "calcium": 5,
            "vitamin_d": 0,
            "vitamin_a": 3,
            "vitamin_b12": 0,
            "vitamin_b6": 0.36,
            "folate": 20,
            "magnesium": 27,
            "potassium": 358,
            "zinc": 0.15,
            "selenium": 1,
            "copper": 0.07,
            "manganese": 0.27,
            "iodine": 0,
        },
    },
    "egg": {
        "calories": 155,
        "fat": 11,
        "protein": 13,
        "carbohydrates": 1.1,
        "micronutrients": {
            "vitamin_c": 0,
            "iron": 1.8,
            "calcium": 56,
            "vitamin_d": 1.1,
            "vitamin_a": 252,
            "vitamin_b12": 1.1,
            "vitamin_b6": 0.13,
            "folate": 54,
            "magnesium": 10,
            "potassium": 126,
            "zinc": 1.2,
            "selenium": 15,
            "copper": 0.06,
            "manganese": 0.02,
            "iodine": 26,
        },
    },
    "chicken breast": {
        "calories": 165,
        "fat": 3.6,
        "protein": 31,
        "carbohydrates": 0,
        "micronutrients": {
            "vitamin_c": 0,
            "iron": 0.9,
            "calcium": 12,
            "vitamin_d": 0,
            "vitamin_a": 16,
            "vitamin_b12": 0.3,
            "vitamin_b6": 0.54,
            "folate": 3,
            "magnesium": 27,
            "potassium": 332,
            "zinc": 0.9,
            "selenium": 22,
            "copper": 0.07,
            "manganese": 0.01,
            "iodine": 0,
        },
    },
    "spinach": {
        "calories": 23,
        "fat": 0.4,
        "protein": 2.9,
        "carbohydrates": 3.6,
        "micronutrients": {
            "vitamin_c": 28,
            "iron": 2.7,
            "calcium": 99,
            "vitamin_d": 0,
            "vitamin_a": 469,
            "vitamin_b12": 0,
            "vitamin_b6": 0.19,
            "folate": 194,
            "magnesium": 79,
            "potassium": 558,
            "zinc": 0.53,
            "selenium": 1.4,
            "copper": 0.13,
            "manganese": 0.89,
            "iodine": 0,
        },
    },
    "rice": {
        "calories": 130,
        "fat": 0.3,
        "protein": 2.7,
        "carbohydrates": 28,
        "micronutrients": {
            "vitamin_c": 0,
            "iron": 0.8,
            "calcium": 10,
            "vitamin_d": 0,
            "vitamin_a": 0,
            "vitamin_b12": 0,
            "vitamin_b6": 0.08,
            "folate": 8,
            "magnesium": 12,
            "potassium": 35,
            "zinc": 0.4,
            "selenium": 1.5,
            "copper": 0.06,
            "manganese": 0.58,
            "iodine": 0,
        },
    },
    "roti": {
        "calories": 304,
        "fat": 1.4,
        "protein": 9.3,
        "carbohydrates": 64,
        "micronutrients": {
            "vitamin_c": 0,
            "iron": 2.7,
            "calcium": 22,
            "vitamin_d": 0,
            "vitamin_a": 0,
            "vitamin_b12": 0,
            "vitamin_b6": 0.2,
            "folate": 60,
            "magnesium": 57,
            "potassium": 129,
            "zinc": 1.2,
            "selenium": 8,
            "copper": 0.2,
            "manganese": 1.3,
            "iodine": 0,
        },
    },
    "avocado": {
        "calories": 160,
        "fat": 15,
        "protein": 2,
        "carbohydrates": 9,
        "micronutrients": {
            "vitamin_c": 10,
            "iron": 0.5,
            "calcium": 12,
            "vitamin_d": 0,
            "vitamin_a": 24,
            "vitamin_b12": 0,
            "vitamin_b6": 0.25,
            "folate": 68,
            "magnesium": 29,
            "potassium": 485,
            "zinc": 0.64,
            "selenium": 0.4,
            "copper": 0.19,
            "manganese": 0.29,
            "iodine": 0,
        },
    },
    "quinoa": {
        "calories": 120,
        "fat": 2,
        "protein": 4,
        "carbohydrates": 21,
        "micronutrients": {
            "vitamin_c": 0,
            "iron": 1.4,
            "calcium": 17,
            "vitamin_d": 0,
            "vitamin_a": 0,
            "vitamin_b12": 0,
            "vitamin_b6": 0.16,
            "folate": 42,
            "magnesium": 64,
            "potassium": 152,
            "zinc": 1.2,
            "selenium": 1.9,
            "copper": 0.19,
            "manganese": 0.69,
            "iodine": 0,
        },
    },
}

# Default fallback nutrient data when AI fails or times out
DEFAULT_FALLBACK_NUTRIENTS = {
    "calories": 0,
    "fat": 0,
    "protein": 0,
    "carbohydrates": 0,
    "micronutrients": {
        "vitamin_c": 0,
        "iron": 0,
        "calcium": 0,
        "vitamin_d": 0,
        "vitamin_a": 0,
        "vitamin_b12": 0,
        "vitamin_b6": 0,
        "folate": 0,
        "magnesium": 0,
        "potassium": 0,
        "zinc": 0,
        "selenium": 0,
        "copper": 0,
        "manganese": 0,
        "iodine": 0,
    },
}
